name: Android CI

on: [push, pull_request]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: build apk
        run: |
          openssl enc -d --aes-256-cbc -K $key -iv $iv -in butterfly-keystore.jks.enc -out butterfly-keystore.jks -salt -pbkdf2
          chmod +x gradlew
          ./gradlew assembleRelease
        env:
          key: ${{ secrets.key }}
          iv: ${{ secrets.iv }}
          store_psd: ${{ secrets.store_psd }}
          key_alias: ${{ secrets.key_alias }}
          key_psd: ${{ secrets.key_psd }}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  deploy:
    name: Deploy when tags created
    needs: android
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags/')
    steps:
      - name: prepare release
        id: prepare_release
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo ::set-output name=tag_name::$TAG_NAME
      - name: download build result for job apk
        if: steps.prepare_release.outputs.tag_name
        uses: actions/download-artifact@v3
        with:
          name: release-apk
      - name: create release
        id: create_release
        if: steps.prepare_release.outputs.tag_name
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.BUTTERFLY_TOKEN }}
          artifacts: "./app-release.apk"
          allowUpdates: true